-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(PRICE * SALES) TOTAL_SALES
FROM BOOK B, AUTHOR A, BOOK_SALES BS
WHERE TO_CHAR(BS.SALES_DATE, 'YYYYMM') = '202201'
    AND B.BOOK_ID = BS.BOOK_ID
    AND B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, CATEGORY DESC;
