-- 코드를 입력하세요
-- SELECT PRODUCT_CODE, PRICE * SALES_AMOUNT SALES 
-- FROM PRODUCT P
-- JOIN OFFLINE_SALE S
-- ON P.PRODUCT_ID = S.PRODUCT_ID
-- GROUP BY PRODUCT_CODE;

SELECT PRODUCT_CODE, SUM(SALE) SALES
FROM (SELECT PRODUCT_CODE, PRICE * SALES_AMOUNT SALE
        FROM PRODUCT P
        JOIN OFFLINE_SALE S
        ON P.PRODUCT_ID = S.PRODUCT_ID)
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;