SELECT C.CAR_ID, C.CAR_TYPE, (DAILY_FEE * 30 * (1 - DISCOUNT_RATE / 100)) FEE
FROM CAR_RENTAL_COMPANY_CAR C,
     CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
WHERE C.CAR_TYPE = P.CAR_TYPE AND
P.DURATION_TYPE = '30일 이상' AND
C.CAR_TYPE IN ('세단', 'SUV') AND

CAR_ID NOT IN (SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                    WHERE '202211' BETWEEN TO_CHAR(START_DATE, 'YYYYMM') AND TO_CHAR(END_DATE, 'YYYYMM')) AND
(DAILY_FEE * 30 * (1 - DISCOUNT_RATE / 100)) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;