-- 코드를 입력하세요
SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM REST_INFO I,
(SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) SCORE
FROM REST_REVIEW
GROUP BY REST_ID) R
WHERE I.REST_ID = R.REST_ID
    AND ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;