-- 코드를 입력하세요
SELECT YEAR, MONTH, GENDER, USERS
FROM (
    SELECT TO_CHAR(SALES_DATE, 'YYYY') YEAR, TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) MONTH, GENDER, COUNT(DISTINCT U.USER_ID) USERS
    FROM USER_INFO U
    JOIN ONLINE_SALE S
    ON U.USER_ID = S.USER_ID
    GROUP BY TO_CHAR(SALES_DATE, 'YYYY'), TO_CHAR(SALES_DATE, 'MM'), GENDER)
WHERE GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER;