-- 코드를 입력하세요
SELECT O.PRODUCT_ID, PRODUCT_NAME, (AMOUNT * PRICE) TOTAL_SALES
FROM FOOD_PRODUCT P,
    (SELECT PRODUCT_ID, SUM(AMOUNT) AMOUNT
    FROM FOOD_ORDER
    WHERE TO_CHAR(PRODUCE_DATE, 'YYYYMM') = '202205'
    GROUP BY PRODUCT_ID) O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;