-- 코드를 입력하세요
SELECT T.HISTORY_ID
     , TRUNC(T.DURATION * T.DAILY_FEE * (1 - NVL(P.DISCOUNT_RATE, 0) / 100)) AS FEE
  FROM (SELECT H.HISTORY_ID
             , C.CAR_TYPE
             , C.DAILY_FEE
             , H.END_DATE - H.START_DATE + 1 AS DURATION
             , CASE WHEN H.END_DATE - H.START_DATE + 1 BETWEEN 7 AND 29 THEN '7일 이상'
                    WHEN H.END_DATE - H.START_DATE + 1 BETWEEN 30 AND 89 THEN '30일 이상'
                    WHEN H.END_DATE - H.START_DATE + 1 >= 90 THEN '90일 이상'
                END AS DURATION_TYPE
          FROM CAR_RENTAL_COMPANY_CAR C
             , CAR_RENTAL_COMPANY_RENTAL_HISTORY H
         WHERE C.CAR_ID = H.CAR_ID
           AND C.CAR_TYPE = '트럭') T
     , CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
 WHERE T.CAR_TYPE = P.CAR_TYPE(+)
   AND T.DURATION_TYPE = P.DURATION_TYPE(+)
 ORDER BY FEE DESC, T.HISTORY_ID DESC