SELECT  X.FLAVOR
  FROM (SELECT A.FLAVOR
          FROM (SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF) A
         INNER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY GROUP BY FLAVOR) B
            ON A.FLAVOR = B.FLAVOR
         ORDER BY (A.TOTAL_ORDER + B.TOTAL_ORDER) DESC) X
 WHERE ROWNUM <= 3