-- 코드를 입력하세요
SELECT FLAVOR
FROM 
    (SELECT ROWNUM RM, FLAVOR
    FROM (SELECT F.FLAVOR FLAVOR
        FROM FIRST_HALF F
        JOIN JULY J
        ON F.FLAVOR = J.FLAVOR
        GROUP BY F.FLAVOR
        ORDER BY SUM(F.TOTAL_ORDER + J.TOTAL_ORDER) DESC))
WHERE RM <= 3;    

