-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM (SELECT APNT_NO, PT_NO, MCDP_CD, APNT_YMD, MDDR_ID
    FROM APPOINTMENT
    WHERE MCDP_CD = 'CS' 
        AND TO_CHAR(APNT_YMD, 'YYYYMMDD') = '20220413' 
        AND APNT_CNCL_YN = 'N') A,
    DOCTOR D,
    PATIENT P
WHERE MDDR_ID = DR_ID AND A.PT_NO = P.PT_NO
ORDER BY APNT_YMD;
    