-- 코드를 입력하세요

SELECT D.HOUR, COUNT(A.HOUR) COUNT
FROM (SELECT TO_CHAR(DATETIME, 'HH24') HOUR FROM ANIMAL_OUTS) A
RIGHT JOIN (SELECT LEVEL - 1 HOUR FROM DUAL CONNECT BY LEVEL <= 24) D
ON A.HOUR = D.HOUR
GROUP BY D.HOUR
ORDER BY D.HOUR;
