SELECT  USERS.USER_ID AS USER_ID
        ,USERS.NICKNAME AS NICKNAME
        ,FILTER_USERS.TOTAL_SALES AS TOTAL_SALES
FROM    (-- 거래 테이블 사용자별 거래 완료 데이터 가상 VIEW
            SELECT  WRITER_ID AS USER_ID
                    , SUM(PRICE) AS TOTAL_SALES --거래 총 금액
            FROM    USED_GOODS_BOARD
            WHERE   STATUS = 'DONE' --거래 완료 상태
            GROUP BY WRITER_ID
            HAVING  SUM(PRICE) >= 700000 --총 거래금액이 70만원 이상인 경우
        ) FILTER_USERS
        , USED_GOODS_USER USERS
WHERE   USERS.USER_ID = FILTER_USERS.USER_ID
ORDER BY FILTER_USERS.TOTAL_SALES ASC --오름차순(내림차순 DESC)