-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
FROM REST_REVIEW R, MEMBER_PROFILE M,
    (SELECT MEMBER_ID, RANK() OVER(ORDER BY COUNT(MEMBER_ID) DESC) RANK
                    FROM REST_REVIEW
                    GROUP BY MEMBER_ID) N
WHERE R.MEMBER_ID = N.MEMBER_ID AND N.RANK = 1 AND N.MEMBER_ID = M.MEMBER_ID
ORDER BY 3, 2;
