-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) TOTAL_SALES
FROM BOOK_SALES S 
JOIN BOOK B
ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE BETWEEN TO_DATE('20220101', 'YYYYMMDD') AND TO_DATE('20220131', 'YYYYMMDD')
GROUP BY CATEGORY
ORDER BY CATEGORY;
