-- 코드를 입력하세요
SELECT B.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT A,
    (SELECT CATEGORY, MAX(PRICE) MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY) B
WHERE B.CATEGORY = A.CATEGORY AND B.MAX_PRICE = A.PRICE
ORDER BY MAX_PRICE DESC;